name: Updates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  nix-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Update packages
        run: |
          set -Eeu
          skip=(
            'cosmic-manager'
          )
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          nix profile add nixpkgs#jq nixpkgs#nix-update
          nix flake update --commit-lock-file
          nix eval --json .#packageList | jq -r '.[]' | while read i; do
            if [[ "${skip[@]}" =~ $i ]]; then
              echo Skipped $i
              continue
            fi
            nix-update $i -q --flake --commit --version=branch
          done
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          branch: ci/update
          delete-branch: true
          title: "Updates"
          body: |
            Update everything

            See commit messages for details
